export const customTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "comment", foreground: "dcdcdc", fontStyle: "italic" },
    { token: "keyword", foreground: "df769b", fontStyle: "bold" },
    { token: "string", foreground: "49e9a6" },
    { token: "number", foreground: "7060eb" },
    { token: "variable", foreground: "e4b781" },
    { token: "function", foreground: "16a3b6", fontStyle: "bold" },
    { token: "type", foreground: "d67e5c", fontStyle: "italic" },
    { token: "tag", foreground: "e66533", fontStyle: "bold" },
  ],
  colors: {
    "editor.background": "#060606",
    "editor.foreground": "#becfda",
    "editorLineNumber.foreground": "#4d6c80",
    "editorLineNumber.activeForeground": "#61a6d1",
    "editorCursor.foreground": "#EA7773",
    "editor.selectionBackground": "#1679b6cc",
    "editor.lineHighlightBackground": "#003c61ee",
    "editor.lineHighlightBorder": "#003c61",
    "editorIndentGuide.background": "#183c53",
    "editorIndentGuide.activeBackground": "#28658a",
  },
};
